database:
  host: !ENV ${DB_HOST}
  dbname: postgres
  username: !ENV ${DB_USER}
  password: !ENV ${DB_PASSWORD}
  type: !ENV ${DB_TYPE}
  port: 5432
log_level: WARN
security:
  secret_key: !ENV ${SECRET_KEY}
  algorithm: !ENV ${ALGORITHM}
  refresh_token_ttl: !ENV ${REFRESH_TOKEN}
  access_token_ttl: !ENV ${ACCESS_TOKEN}
